### ISSUE TITLE
Return object with headers as keys and data as lists with speed way

### ISSUE THREAD

**Issue by DAmrGharieb** [laslibs/las-js#28]
hi team 
good day

is there is a function that give instantensoly object contain the data with headers in fast way i tried this below but it consume much time

let data: any = {};
    const headers = await myLas.header();

    return new Promise(async (resolve, reject) => {
      const headers = await myLas.header();
      for (let i = 0; i < headers.length; i++) {
        let h = headers[i];
        data[h] = await myLas.column(h);
      }

      resolve(data);
    });

**Comment by iykekings** [comment]
@DAmrGharieb you can do
```ts
async function getDataWithHeaders() {
    const data = await myLas.data();
    const headers = await myLas.header()
    return Object.fromEntries(headers.map((h, i) = [h, data[i]]))
}
```

Let me know if this works for you

**Comment by DAmrGharieb** [comment]
i think there is some thing missing 
i load only the number of headers in my example 29 header curve and the data is not sorted even

**Comment by DAmrGharieb** [comment]
really thanks for you help i made a modification because to adjust each curve to it's data need another map

    return Object.fromEntries(headers.map((x, i) => [x, data.map((y) => y[i])]));
