### ISSUE TITLE
[BUG]: Importing las-js with cyrillic causes error

### ISSUE THREAD

**Issue by dudehydra** [laslibs/las-js#32]
**Describe the bug**
Error when importing file with cyrillic symbols: TypeError: Cannot read properties of undefined (reading 'split') index.js:373

**To Reproduce**
1. Import las with cyrillic symbols 

The error occurs in this section of code:
index.js:373

const unit = obj
                        .trim()
                        .split(/^\w+\s*[.]*s*/)[1] 
                        .split(/\s+/)[0];
                        
When we use this regular expression .split(/^\w+\s*[.]*s*/)[1]                         
  "MD .m  : \r".trim() .split(/^\w+\s*[.]*s*/) the result will be ['', 'm  :']  // English 
  "МД .m  : \r".trim().split(/^\w+\s*[.]*s*/)  the result will be ['МД .m  :'] // Cyrillic
  
 I think you can replace it with .split(/^[\p{L}\p{M}]+\s*[.]*s*/u)[1] and it will work and with English characters and with Cyrillic

**Comment by iambenkay** [comment]
Interesting! You can go ahead and create a PR solving this @dudehydra

**Comment by dudehydra** [comment]
Thanks for the info.
The strange thing is that some companies use Cyrillic in las 2.0.
