### ISSUE TITLE
[BUG]: las-js fails reading data on Node.js v20.3.1

### ISSUE THREAD

**Issue by hannehanen** [laslibs/las-js#35]
**Describe the bug**
Unable to read data from either Las.data() or Las.header().
And your example show 
"const myLas = new Lasjs(data, { loadFile: false });"
I guess the example-text is wrong (Lasjs).
Anyway im very exited to test this out.

**To Reproduce**
Image tells it all.

**Expected behavior**
Expected to see console.log with data from .las file.

**Screenshots**
![image](https://github.com/laslibs/las-js/assets/29543264/de7a80e2-6073-4b69-8523-157cb9aca089)

**Comment by iambenkay** [comment]
Your input data is likely not a valid las file

**Comment by iambenkay** [comment]
Then most likely wrong format used by translator. Note that the library supports only las 2.0

**Comment by hannehanen** [comment]
Ah ok. Thats it. i see they are using version 1.2.

"18D022_670_55_0025.las (tillhandahålls packad i .laz) Punktfiler i LAS-format version 1.2, point data record format 1, komprimerade med Laszip. I filnamnet ingår identiteten för skanningsområdet samt koordinaterna för indexrutans nedre vänstra hörn. "

**Comment by iykekings** [comment]
@hannehanen there is a PR to add support for version 3 #34 but I'm not when/if there would be support for version 1. Maybe if we rewrite the libraries in Rust. Nerd-snipping @iambenkay

**Comment by iykekings** [comment]
I have also added Node 20.x to our CI and all the tests are passing

**Comment by hannehanen** [comment]
Thank you.
